name: Build Nuxt3 Application

on:
    push:
        branches:
            - main
            - patch-1
            
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.2.2
              
            - run: corepack enable
            - name: Setup Node.js
              uses: actions/setup-node@v4.1.0
              with:
                  node-version: '20'
                  registry-url: "https://registry.npmjs.org/"
                  cache: "pnpm"

            - name: Cache apt
              uses: actions/cache@v4.1.2
              with:
                path: |
                  /var/lib/apt/lists
                  /var/cache/apt
                key: ${{ runner.os }}-apt
            
            - name: Cache playwright
              uses: actions/cache@v4.1.2
              with:
                path: |
                  ~/.cache/ms-playwright
                key: ${{ runner.os }}-playwright

            - name: Install playwright
              run: pnpx playwright install --with-deps
            
            - name: Install dependencies
              run: pnpm install

            - name: Generate static site
              run: pnpm run generate
